language: go
go:
  - 1.6
  - 1.7
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master
before_install:
  - export GO15VENDOREXPERIMENT=1
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mjtruog@gmail.com
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    template:
      - "%{repository_slug} (%{branch} - %{commit}) %{author}: %{commit_message}"
      - "View Changes %{compare_url}"
      - "Build #%{build_number}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
